#!/bin/bash

#################################
# System 
#################################

alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias suspend='sudo pm-suspend'

alias bigf= 'find / -xdev -type f -size +500M'  # display "big" files > 500M
alias config='/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME'

#################################
# ls 
#################################

# ls replacement
alias ls="exa -abghHliS"
alias la="exa -abghHliS"

# cat replacement
alias cat="bat"

alias du="dust"
alias df="duf -all"
alias pint="gping"
alias curl="curlie -v"

# jump to root folder of git repo
alias cdr="_cdr"

# function to jump into root folder of a git repo
_cdr() {
	cd "$(git rev-parse --show-toplevel)"
}

#################################
# navigation
#################################

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

#################################
# git
#################################

alias gb="_gb"
alias gbt="_gbt"
alias gs="_gs"
alias gmaster="gs master"
alias gmain="gs main"
alias gdev="gs dev"
alias gco="_gco"
alias gfeat="_gfeat"
alias gfix="_gfix"
alias gtest="_gtest"
alias gdocs="_gdocs"
alias gstyle="_gstyle"
alias grefactor="_grefactor"
alias gperf="_gperf"
alias gchore="_gchore"
alias gpu="git pull && git lg"
alias gfp="git push --force-with-lease"
alias goops="_goops"
alias greset="_gr"


_gs () {
	git checkout $1
	git pull
}

_gb() {
	git checkout -b $1
}

_gbt() {
	git checkout -b task/$1
}

_gr() {
	git reset --hard
	git clean -f -d
}

_goops() {
	git add .
	git commit --amend --no-edit
}

_gco() {
	git add .
	git commit -m "$@"
}

_gfeat() {
	if [[ "$#" -eq 1 ]]; then
		gco "feat: $1"
	else
		gco "feat($1): $2"
	fi
}

_gfix() {
	if [[ "$#" -eq 1 ]]; then
		gco "fix: $1"
	else
		gco "fix($1): $2"
	fi
}

_gtest() {
	if [[ "$#" -eq 1 ]]; then
		gco "test: $1"
	else
		gco "test($1): $2"
	fi
}

_gdocs() {
	if [[ "$#" -eq 1 ]]; then
		gco "docs: $1"
	else
		gco "docs($1): $2"
	fi
}

_gstyle() {
	if [[ "$#" -eq 1 ]]; then
		gco "style: $1"
	else
		gco "style($1): $2"
	fi
}

_grefactor() {
	if [[ "$#" -eq 1 ]]; then
		gco "refactor: $1"
	else
		gco "refactor($1): $2"
	fi
}

_gperf() {
	if [[ "$#" -eq 1 ]]; then
		gco "perf: $1"
	else
		gco "perf($1): $2"
	fi
}

_gchore() {
	if [[ "$#" -eq 1 ]]; then
		gco "chore: $1"
	else
		gco "chore($1): $2"
	fi
}

#################################
# cp / mv / rm
#################################

alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -i"

#################################
# grep
#################################

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#################################
# time
#################################

alias time='/usr/bin/time'

#################################
# personal
#################################

# Folders
alias work="cd $HOME/dev"
alias doc="cd $HOME/Documents"
alias dow="cd $HOME/Downloads"
alias dot="cd $HOME/dotfiles"
# alias study="cd $HOME/Documents/Obsidian/UZH"
alias ctf="cd $HOME/dev/CTF"

#################################
# scripts
#################################

alias nvimrc='nvim ~/dotfiles/mac/nvim/'
alias gitconfig="nvim ~/dotfiles/mac/.gitconfig"
alias ip="ipconfig getifaddr en0"

# navigate to global ssh directory
alias sshhome="cd ~/.ssh"
# edit global ssh configuration
alias sshconfig="nvim ~/.ssh/config"

# Get macOS Software Updates, and update Homebrew, and their installed packages
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup;'

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"